### ISSUE TITLE
No such module 'CommonCryptoModule'

### ISSUE THREAD

**Issue by Alex111one** [christophhagen/SignalProtocolSwift#2]
Hello. 
When I'm trying to import SignalProtocolSwift into the project via Cocoapods, by inserting <pod 'SignalProtocolSwift', git: 'https://github.com/christophhagen/SignalProtocolSwift.git'> in my podfile, and then building the project, I'm getting an error in SignalCommonCrypto.swift, that says: 
No such module 'CommonCryptoModule'.
And even if I add this module manually to the project, there's still an error that says: "no such module CommonCryptoBridge" and "Could not build Objective-C module 'CommonCryptoModule'".
The overall implementation looks really great. But I can't handle this issue to build and use it. Please, leave some comments about this issue. 
Thanks.

**Comment by christophhagen** [comment]
I didn't realise that my approach using CommonCrypto would result in this error, but I have confirmed that it exists. The framework can use the CommonCrypto module without problems, but it is somehow not included when using cocoapods. Maybe the podspec needs to be updated for that, but I don't know how. Any hints are welcome.

I've struggled for some time with this. The underlying problem has to do with the CommonCrypto implementation: It doesn't have modular headers, so it's not possible to import them in the Umbrella header of the framework. There are some workarounds [here](https://stackoverflow.com/questions/25248598/importing-commoncrypto-in-a-swift-framework#29189873), but all of these approaches have different problems.

For now I'm rewriting the framework to require the users to implement the CryptoProvider themselves, please check the readme for details.

**Comment by christophhagen** [comment]
I found a solution that seems to work now, there should be no more errors when using Cocoapods. I've moved the Elliptic curve definitions to a separate framework which needs to be added to the pod spec as well. Please check the readme file

**Comment by Alex111one** [comment]
Thanks a lot, Christoph. The issue with 'CommonCryptoModule' and Cocoapods was resolved. And thanks for the test implementation example. The overall implementation looks awesome!
